In [153]:
import pandas as pd
UBS_df = pd.read_excel("UBS_PG16.xlsx",header=6, skip_footer=3)
UBS_df.drop(columns = ['Unnamed: 7', 'Valued in USD'], inplace = True)
UBS_df.rename(index = str, columns = {
    'By date': 'Value Date',
    'Unnamed: 1': 'Booking Text',
    'Unnamed: 2': 'Transaction Tax',
    'Unnamed: 3': 'Descritption',
    'Unnamed: 4': 'Ccy',
    'Unnamed: 5': 'Amount',
    'Unnamed: 6': 'Purchase Price'
}, inplace=True)
UBS_df.drop(UBS_df.index[0:8], inplace=True)
UBS_df.reset_index(drop=True,inplace=True)
UBS_df.drop(UBS_df.index[[2,3,4,5,8,9,10,11,14,15,16,19,20,21,24,25,26]], inplace=True)
UBS_df.reset_index(drop=True,inplace=True)
UBS_df['Purchase Price'] = UBS_df['Amount']
UBS_df['Amount'] = UBS_df['Ccy']
UBS_df.fillna(value='', inplace=True)
UBS_df['Ccy'] = UBS_df['Ccy'].map(lambda x: str(x))
UBS_df['Amount'] = UBS_df['Descritption'].str.extract('([0-9 ]*$)')
UBS_df['Amount'] = UBS_df['Amount']+ UBS_df['Ccy']
UBS_df['Descritption'].replace('(-[0-9 ]*$)', '', regex=True, inplace=True)
UBS_df['Ccy'].replace('([0-9 ]*)', '', regex=True, inplace=True)
UBS_df['Ccy'] = UBS_df['Descritption'].str.extract('([A-Z ]*$)',expand=True)
UBS_df['Descritption'].replace('([A-Z ]*$)', '', regex=True, inplace=True)
UBS_df['Transaction Tax'].replace('', '0', regex=True, inplace=True)
UBS_df['Purchase Price'].replace('', '0', regex=True, inplace=True)
UBS_df['Purchase Price'] = UBS_df['Purchase Price'].map(lambda x: float(x))
UBS_df['Transaction Tax'] = UBS_df['Transaction Tax'].map(lambda x: float(x))
UBS_df['Amount'].replace('\s', '', regex=True, inplace=True)
UBS_df['Amount'] = UBS_df['Amount'].map(lambda x: float(x))
UBS_df['Value Date'] = pd.to_datetime(UBS_df['Value Date']).dt.strftime('%d/%m/%Y')
UBS_df

c:\users\ganesh\appdata\local\programs\python\python36-32\lib\site-packages\ipykernel_launcher.py:21: FutureWarning: currently extract(expand=None) means expand=False (return Index/Series/DataFrame) but in a future version of pandas this will be changed to expand=True (return DataFrame)

,Value Date,Booking Text,Transaction Tax,Descritption,Ccy,Amount,Purchase Price
0,28/02/2018,Purchase,0.0,You bought,EUR,1000000.0,0.000000
1,03/02/2018,FX Spot,0.0,You sold,USD,1222510.0,1.222510
2,28/02/2018,Sale,0.0,You sold,EUR,3000000.0,0.000000
3,03/02/2018,FX Spot,0.0,You bought,USD,3659400.0,1.219800
4,03/01/2018,Purchase,0.0,You bought,EUR,3000000.0,0.000000
5,03/06/2018,FX Forward,0.0,You sold,USD,3693753.0,1.231251
6,03/01/2018,Purchase,0.0,You bought,EUR,2000000.0,0.000000
7,03/06/2018,FX Forward,0.0,You sold,USD,2464202.0,1.232101
8,03/01/2018,Purchase,0.0,You bought,EUR,2000000.0,0.000000
9,03/06/2018,FX Forward,0.0,You sold,USD,2447800.0,1.223900